version: '3'
services:
  web:
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
    ports:
    - "5000:5000"
    volumes:
    - ..:/app:ro
    - logvolume01:/var/log
    environment:
    - FLASK_APP=__init__.py
    - FLASK_ENV=development
    #command: python -m flask run

  proxy:
    image: nginx:stable
    ports:
    - "8888:80"
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
volumes:
  logvolume01: {}